site_name: AudioMail Documentation
site_description: AI-powered voice-to-email tool with local processing
site_author: AudioMail Team
site_url: https://github.com/sina5/audiomail

repo_name: sina5/audiomail
repo_url: https://github.com/sina5/audiomail

theme:
  name: material
  palette:
    # Palette toggle for dark mode
    - scheme: slate
      primary: deep purple
      accent: purple
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
    # Palette toggle for light mode
    - scheme: default
      primary: deep purple
      accent: purple
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
  
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.highlight
    - search.share
    - content.code.copy
    - content.code.annotate

plugins:
  - search

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - md_in_html

nav:
  - Home: index.md
  - Installation: installation.md
  - Usage:
    - Getting Started: usage.md
    - Web UI: ui.md
    - Command Line: cli.md
  - Configuration: configuration.md
  - Troubleshooting: troubleshooting.md
  - Deployment: deployment.md